baseurl = "http://www.mattnworb.com/"
languageCode = "en-us"
title = "Matt Brown"

# use hyde for now
theme = "hyde"

[params]
  DateForm = "Mon, Jan 2, 2006"
  DateFormFull = "Mon, Jan 2, 2006"
  name = "Matt Brown"
  bio = "person"
  Title = "Matt Brown"
  twitterName = "mattnworb"
  githubName = "mattnworb"
