baseurl = "http://www.mattnworb.com/"
languageCode = "en-us"
title = "Matt Brown"

#Paginate = 0

[author]
    name = "Matt Brown"

theme = "lanyon"

[params]
  DateForm = "Mon, Jan 2, 2006"
  DateFormFull = "Mon, Jan 2, 2006"
  name = "Matt Brown"
  bio = "person"
  Title = "Matt Brown"
  Tagline = "content for you"

  #gravatarHash = "c11c60c7e6d29cb4b87f3c0a3b692181"

  twitter = "https://www.twitter.com/mattnworb"
  twitterName = "mattnworb"

  github = "https://www.github.com/mattnworb"
  githubName = "mattnworb"

