baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"

# use hyde for now
theme = "hyde"

[params]
DateForm = "Mon, Jan 2, 2006"
DateFormFull = "Mon, Jan 2, 2006"
